config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/restaurants", to: "restaurants#index", as: "restaurants"
  get '/restaurants/all', to: 'restaurants#all', as: "all_restaurants"
  post "/restaurants", to: "restaurants#create"
  get "/restaurants/new", to: "restaurants#new", as: "new_restaurant"
  get "/restaurants/:id", to: "restaurants#show", as: "restaurant"

  put "/restaurants/:id", to: "restaurants#update"
  patch "/restaurants/:id", to: "restaurants#update"
  get "/restaurants/:id/edit", to: "restaurants#edit", as: "edit_restaurant"
  delete '/restaurants/:id', to: "restaurants#destroy", as: "delete_restaurant"

  post "/reviews", to: "reviews#create", as: "review"
  delete '/reviews/:id', to: "reviews#destroy", as: "delete_review"
  root 'restaurants#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
        can :destroy, Review
      else
        can [:read, :all], [Restaurant, Review]
      end

      if user.moderator?
        can :destroy, Review
        cannot :destroy, Restaurant
        cannot :update, Restaurant
      end
    
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :title, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :food_type, presence: true

  has_many :reviews

  def next
    self.class.where("created_at > ?", created_at).order(created_at: :asc).first
  end
  
  def previous
    self.class.where("created_at < ?", created_at).order(created_at: :asc).last
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    all_restaurants_path 
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  authorize_resource
  def index
  end

  def all
    # @restaurants = Restaurant.all.order('created_at DESC')
    @restaurants = Restaurant.paginate(page: params[:page], per_page: 6)
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      flash[:notice] = "Restaurant successfully listed"
      redirect_to restaurant_path(@restaurant)
      #same as redirect_to @restaurant
    else
      render 'new'
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @restaurant1 = Restaurant.find(params[:id])

    @restaurants = Restaurant.all.order('created_at DESC')

    @previous_restaurant = @restaurant1.next
    @next_restaurant = @restaurant1.previous
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update(restaurant_params)
      flash[:notice] = "Restaurant successfully updated"
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = "Restaurant successfully deleted"
   
    redirect_to all_restaurants_path
  end

  private

  def restaurant_params
    params.permit(:title, :address, :description, :food_type)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.create(review_params)
    redirect_to restaurant_path(@restaurant.id)
  end

  def destroy
    @review = Review.find(params[:id])
    @restaurant = @review.restaurant

    @review.destroy

    redirect_to restaurant_path(@restaurant)
  end

  private
  def review_params
    params.permit(:title, :content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_navbar.html.erb
<div class="con-nav">
  <nav id="navbar" class="navbar">
    <% if user_signed_in? %>
    <ul class="nav navbar-nav">
      <li><%= link_to 'Home', all_restaurants_path, class: "home" %></li>
    </ul>
    <% else %>
    <ul class="nav navbar-nav">
      <li><%= link_to 'Home', root_path, class: "home" %></li>
    </ul>
    <% end %>
    <ul class="nav navbar-nav pull-right">
      <% if user_signed_in? %>
        <%# <li class="dropdown"> %>
          <%# <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <span class="caret"></span>
          </a> %>
          <ul class= "nav-right" role="menu">
            <li><%= link_to 'Profile', edit_user_registration_path, class: "nav-pad white-link" %></li>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "nav-pad white-link" %></li>
          </ul>
        <%# </li> %>
      <% else %>
        <li><%= link_to 'Log In', new_user_session_path, class: "nav-pad white-link" %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path, class: "nav-pad white-link" %></li>
      <% end %>
    </ul>
  </nav>
</div>
<%# <% flash.each do |key, value| %>
  <%# <%= value %> 
<%# <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails01Restaurants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', "https://fonts.googleapis.com/css?family=Abril+Fatface", 
    media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# <% unless action_name == "index" %>
      <%= render 'layouts/navbar' %>
    <%# end %>

    <%# <% if flash[:notice] %>
      <%# <div class="notice"><%= flash[:notice] %> 
    <%# <% end %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_restaurants.html.erb
<div class="row">
    <% obj.each_with_index do |restaurant, index| %>
    <div class="col-lg-4 col-sm-6 col-xs-12">
      <% total = [] %>
      <% restaurant.reviews.each do |review| %>
        <% total << review.rating %>
      <% end %>
      <div class="thumbnail" style="border: 1px solid black;">
        <p><%= restaurant.title %> - <%= restaurant.food_type %></p>
        <% if restaurant.reviews.length == 0 %>
          <p><%= restaurant.title %> has no reviews</p>
        <% else %>
          <p>Reviews: <%= restaurant.reviews.count %></p>
        <% end %>
        <p>Review Average: 
          <% if total.count > 0 %>
            <p><%=  total.sum.to_f.fdiv(restaurant.reviews.count).round(2) %> out of 5</p>
          <% else %>
            <p><%= restaurant.title %> has no reviews</p>
          <% end %>
        <%= link_to "show", restaurant_path(restaurant.id) %>
        <% if can? :update, restaurant %>
          <%= link_to "edit", edit_restaurant_path(restaurant.id) %>
          <%= link_to 'delete', delete_restaurant_path(restaurant.id),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
         <% end %>
      </div>
    </div>
    <% end %>
  </div>

app/views/restaurants/all.html.erb
 <div class="container"> 
  <h1 class="restaurant-title">Restaurants</h1>
  <%= link_to "List New Restaurant", new_restaurant_path %>
  <%= will_paginate @restaurants %>
  <%= render 'restaurants', obj: @restaurants %>
</div>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<form action="<%= restaurant_path(params[:id]) %>" method="POST" >
  <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />

  <input type="hidden" name="_method" value="patch" />

  <label for="title">Title</label>
  <input type="text" name="title" id="title" value="<%= @restaurant.title %>"/>

  <label for="address">Address</label>
  <input type="text" name="address" name="address" id="address" value="<%= @restaurant.address %>"/>

  <label>Description</label>
  <input type="textarea" name="description" id="description" value="<%= @restaurant.description %>" />

  <label for="food_type">Food type</label>
  <input type="text" name="food_type" id="food_type"  value="<%= @restaurant.food_type %>"/>

  <input type="submit" value="Update" />
</form>

<%= link_to "Back", all_restaurants_path %>

app/views/restaurants/index.html.erb
<div class="main">
  <div class="index-container"></div>
  <%# <div href="#" class="home-button disabled">EAT</div> %>
</div>

app/views/restaurants/new.html.erb
<h1>Create A New Restaurant</h1>

<form action="<%= restaurants_path %>" method="POST" >
  <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />

  <% if @restaurant.errors.any? %>
  <div id="error_explanation">
    <h2>
    <%= pluralize(@restaurant.errors.count, "error") %> prohibited
    this article from being saved:
    </h2>
    <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <label for="title">Title</label>
  <input type="text" name="title" id="title"/>

  <label for="address">Address</label>
  <input type="text" name="address" id="address"/>

  <label>Description</label>
  <input type="textarea" name="description" id="description" />

  <label for="food_type">Food type</label>
  <input type="text" name="food_type" id="food_type" />

  <input type="submit" value="Create" />
</form>

<%= link_to "Back", all_restaurants_path %>

app/views/restaurants/show.html.erb
<%= link_to "Restaurants Listing", all_restaurants_path %>
<%= link_to "Previous", @next_restaurant if @restaurant != @restaurants.last %>
<%= link_to "Next", @previous_restaurant if @restaurant != @restaurants.first %>



<h2><%= @restaurant.title %></h2>

<h3>Food Type</h3>
<p><%= @restaurant.food_type %></p>

<h3>Address</h3>
<p><%= @restaurant.address %></p>

<h3>Description</h3>
<p><%= @restaurant.description %></p>
<% if can? :update, @restaurant.reviews.all %>
<h3>Add a Review</h3>

<form action="<%= review_path %>" method="POST" >
  <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />
  <input type="hidden" value="<%= @restaurant.id %>" name="restaurant_id" />

  <label for="title">Title</label>
  <input type="text" name="title" id="title"/>

  <label for="content">Content</label>
  <input type="text" name="content" id="content"/>

  <label for="rating">Rating</label>
  <select name="rating">
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
  </select>

  <input type="submit" value="Create" />
</form>
<% end %>
<div class="review-conatiner">
  <h3 style="text-align: center;">Reviews</h3>
  <div style="border: 1px solid black; text-align: center;">
  <% total = [] %>
    <% @restaurant.reviews.each do |review| %>
      <div>
        <h3>Title</h3>
        <h3><%= review.title %></h3>
        <h3>Review</h3>
        <h3><%= review.content %></h3>
        <h3>Rating</h3>
          <% total << review.rating %>
        <h3><%= review.rating %> out of 5</h3>
          <%# <% total += review.rating %> 
        <%# <h3><%= review. %>
        <% if can? :destroy, Review %>
            <%= link_to 'delete', delete_review_path(review.id),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
      <hr>
    <% end %>
    <% if total.count > 0 %>
        <h3>Average Rating</h3>
        <h4><%=  total.sum.to_f.fdiv(@restaurant.reviews.count).round(2) %> out of 5</h4>
    <% else %>
        <h4><%= @restaurant.title %> has no reviews</h4>
    <% end %>    <%# <h4><%= @restaurant.reviews.count %>
  </div>
</div>


<%= link_to "Restaurants Listing", all_restaurants_path %>